### ISSUE TITLE
10.2.7 update?

### ISSUE THREAD

**Issue by dblanch369** [ascott18/ImprovedStableFrame#9] opened 2024-05-10 00:50 UTC
Just curious if you will be updating this for the stable changes in 10.2.7.   I get this LUA error loading in.

7x ...eImprovedStableFrame/ImprovedStableFrame.lua:7: attempt to perform arithmetic on global 'NUM_PET_STABLE_PAGES' (a nil value)
[string "@ImprovedStableFrame/ImprovedStableFrame.lua"]:7: in main chunk

Locals:
clientVersion = 100207
wow_900 = true
wow_800 = true
wow_503 = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = ""
(*temporary) = " "
(*temporary) = " "
(*temporary) = " "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on global 'NUM_PET_STABLE_PAGES' (a nil value)"

**Comment by WhyDaRumGone** [comment] 2024-05-18 05:35
I too am interested but suspect this might require a rework

**Comment by KrakenLatte** [comment] 2024-05-19 20:49
I too would like an update to this! The new base stables UI is neat, but I really do prefer the "bagnon-like" style for organizing my hunter pets. Please!

**Comment by ascott18** [comment] 2024-08-08 23:46
If it wasn't already clear from [all](https://github.com/ascott18/ImprovedStableFrame/issues/8) of [the](https://github.com/ascott18/ImprovedStableFrame/issues/7) other issues to anyone else coming across this one, this addon will never again be update for retail. I only left this issue open because I got tired of closing the the duplicates.

**Comment by ascott18** [comment] 2024-08-08 23:48
Duplicate of #7.

**Closed as not planned by ascott18** 2024-08-08 23:48 UTC

**Comment by TheKeymaster21** [comment] 2025-05-06 22:56
I check back occasionally to see if this is working again and saw the responses. I too agree with KrakenLatte that while the new base UI is better than the older base UI, it still pales into comparison to the "bagnon-like" style of this addon for organizing your pets. 

> If it wasn't already clear from [all](https://github.com/ascott18/ImprovedStableFrame/issues/8) of [the](https://github.com/ascott18/ImprovedStableFrame/issues/7) other issues to anyone else coming across this one, this addon will never again be update for retail. I only left this issue open because I got tired of closing the the duplicates.

Is this open for someone else to update then?

**Comment by ascott18** [comment] 2025-05-07 13:41
Its not a matter of "update". All of the assets, the Blizzard APIs, even the concept of "slots" - everything behind this addon doesn't exist anymore. This addon just made some tweaks to Blizzard's UI. It did not provide a complete replacement of Blizzard's old UI. None of those things that it tweaked exist anymore.

Since I am not the official global gatekeeper of addons, any person is free to create a brand new addon that achieves a similar effect. But it isn't going to be this one.
