### ISSUE TITLE
Update for 10.2.7?

### ISSUE THREAD

**Issue by b-morgan** [ascott18/ImprovedStableFrame#8] opened 2024-05-08 14:15 UTC
Update for 10.2.7?
```
1x ...eImprovedStableFrame/ImprovedStableFrame.lua:7: attempt to perform arithmetic on global 'NUM_PET_STABLE_PAGES' (a nil value)
[string "@ImprovedStableFrame/ImprovedStableFrame.lua"]:7: in main chunk

Locals:
clientVersion = 100207
wow_900 = true
wow_800 = true
wow_503 = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = ""
(*temporary) = " "
(*temporary) = " "
(*temporary) = " "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on global 'NUM_PET_STABLE_PAGES' (a nil value)"
```

**Comment by ascott18** [comment] 2024-05-09 03:56
Duplicate of #7

**Closed as not planned by ascott18** 2024-05-09 03:56 UTC
