### ISSUE TITLE
10.1.7 LUA Errors

### ISSUE THREAD

**Issue by vezevez** [ascott18/ImprovedStableFrame#6] opened 2023-09-07 04:42 UTC
1x ...eImprovedStableFrame/ImprovedStableFrame.lua:102: attempt to index global 'PetStableModel' (a nil value)
[string "@ImprovedStableFrame/ImprovedStableFrame.lua"]:102: in main chunk

Locals:
clientVersion = 100107
wow_900 = true
wow_800 = true
wow_503 = true
maxSlots = 200
NUM_PER_ROW = 10
heightChange = nil
widthDelta = 315
heightDelta = 204
f = ImprovedStableFrameSlots {
 0 = <userdata>
 NineSlice = Frame {
 }
 layoutType = "InsetFrameTemplate"
 Bg = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 485
(*temporary) = <userdata>
(*temporary) = 40
(*temporary) = 692
(*temporary) = 602
(*temporary) = <function> defined =[C]:-1
(*temporary) = PetStableFrame {
 0 = <userdata>
 LeftInset = PetStableLeftInset {
 }
 SetScript = <function> defined =[C]:-1
 SetHeight = <function> defined =[C]:-1
 BottomInset = PetStableBottomInset {
 }
 SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:102
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:98
 SetPortraitTextureRaw = <function> defined @SharedXML/PortraitFrame.lua:84
 SetPortraitToClassIcon = <function> defined @SharedXML/PortraitFrame.lua:92
 TitleContainer = Frame {
 }
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @SharedXML/PortraitFrame.lua:32
 SetWidth = <function> defined =[C]:-1
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 SetTitleOffsets = <function> defined @SharedXML/PortraitFrame.lua:54
 SetBorder = <function> defined @SharedXML/PortraitFrame.lua:67
 layoutType = "PortraitFrameTemplate"
 SetFrameLevelsFromBaseLevel = <function> defined @SharedXML/PortraitFrame.lua:120
 SetPortraitToBag = <function> defined @SharedXML/PortraitFrame.lua:80
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:88
 SetPortraitToUnit = <function> defined @SharedXML/PortraitFrame.lua:76
 Bg = PetStableFrameBg {
 }
 GetPortrait = <function> defined @SharedXML/PortraitFrame.lua:63
 SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 SetPortraitToAsset = <function> defined @SharedXML/PortraitFrame.lua:72
 SetPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:106
 CloseButton = PetStableFrameCloseButton {
 }
 SetPoint = <function> defined =[C]:-1
 page = 1
 PortraitContainer = Frame {
 }
 PetStableModelScene = PetStableModelScene {
 }
 Inset = PetStableFrameInset {
 }
}
(*temporary) = 692
(*temporary) = -692
(*temporary) = -602
(*temporary) = 602
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'PetStableModel' (a nil value)"

---

1x ImprovedStableFrame/ImprovedStableFrame.lua:1 (null)

---

1x Interface\FrameXML\Bindings.xml:1 ImprovedStableFrame/ImprovedStableFrame.lua:1 (null)

**Comment by ascott18** [comment] 2023-09-07 04:56
Duplicate of #5

**Closed as not planned by ascott18** 2023-09-07 04:56 UTC
